spring:
  application:
    name: configserver
  cloud:
    config:
      profiles:
        active: native
      # name: bootstrap
      server:
        bootstrap: true
        # native:
          # searchLocations: file:/C:/Users/sapang/Downloads/config-repo
        git:
          # uri: file:/C:/Users/sapang/Downloads/config-repo
          uri: https://github.com/spring-cloud-samples/config-repo
encrypt:
  failOnError: false
  keyStore:
    location: classpath:keystore.jks
    password: ${KEYSTORE_PASSWORD:foobar} # don't use a default in production
    alias: test